"""initial schema

Revision ID: 3bb545f8e255
Revises: 
Create Date: 2026-08-08 23:17:14.637788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bb545f8e255'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epci',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('parametre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cdparametre_sandre', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('unite', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cdparametre_sandre'),
    sa.UniqueConstraint('code')
    )
    op.create_table('region',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('reseau',
    sa.Column('cdreseau', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('cdreseau')
    )
    op.create_table('departement',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('code_region', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['code_region'], ['region.code'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('commune',
    sa.Column('code_insee', sa.String(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('code_departement', sa.String(), nullable=False),
    sa.Column('code_epci', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['code_departement'], ['departement.code'], ),
    sa.ForeignKeyConstraint(['code_epci'], ['epci.code'], ),
    sa.PrimaryKeyConstraint('code_insee')
    )
    op.create_table('mesure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('referenceprel', sa.String(), nullable=False),
    sa.Column('parametre_id', sa.Integer(), nullable=False),
    sa.Column('code_insee', sa.String(), nullable=False),
    sa.Column('cdreseau', sa.String(), nullable=True),
    sa.Column('date_prel', sa.Date(), nullable=False),
    sa.Column('valeur', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cdreseau'], ['reseau.cdreseau'], ),
    sa.ForeignKeyConstraint(['code_insee'], ['commune.code_insee'], ),
    sa.ForeignKeyConstraint(['parametre_id'], ['parametre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('referenceprel', 'parametre_id', 'code_insee')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mesure')
    op.drop_table('commune')
    op.drop_table('departement')
    op.drop_table('reseau')
    op.drop_table('region')
    op.drop_table('parametre')
    op.drop_table('epci')
    # ### end Alembic commands ###
