"""add mesure conclusion column

Revision ID: 71bf721589cc
Revises: 77b34e1cc2bb
Create Date: 2026-08-19 21:32:21.494789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71bf721589cc'
down_revision: Union[str, Sequence[str], None] = '77b34e1cc2bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesure', sa.Column('conclusion', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mesure', 'conclusion')
    # ### end Alembic commands ###
