"""add lookup indexes

Revision ID: 77b34e1cc2bb
Revises: 3bb545f8e255
Create Date: 2026-08-08 23:29:41.954183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b34e1cc2bb'
down_revision: Union[str, Sequence[str], None] = '3bb545f8e255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_commune_code_departement'), 'commune', ['code_departement'], unique=False)
    op.create_index(op.f('ix_commune_code_epci'), 'commune', ['code_epci'], unique=False)
    op.create_index(op.f('ix_departement_code_region'), 'departement', ['code_region'], unique=False)
    op.create_index(op.f('ix_mesure_code_insee'), 'mesure', ['code_insee'], unique=False)
    op.create_index(op.f('ix_mesure_parametre_id'), 'mesure', ['parametre_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mesure_parametre_id'), table_name='mesure')
    op.drop_index(op.f('ix_mesure_code_insee'), table_name='mesure')
    op.drop_index(op.f('ix_departement_code_region'), table_name='departement')
    op.drop_index(op.f('ix_commune_code_epci'), table_name='commune')
    op.drop_index(op.f('ix_commune_code_departement'), table_name='commune')
    # ### end Alembic commands ###
