"""add mesure valeur_libelle column

Revision ID: 79065f11cc10
Revises: 71bf721589cc
Create Date: 2026-08-19 21:51:48.627654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79065f11cc10'
down_revision: Union[str, Sequence[str], None] = '71bf721589cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mesure', sa.Column('valeur_libelle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mesure', 'valeur_libelle')
    # ### end Alembic commands ###
